### ISSUE TITLE
ConnectionError: All APIs are unreachable.

### ISSUE THREAD

**Issue by jcreem** [remem9527/bchmemo#6]
Trying a pretty simple test case:

from bchmemo import MemoUser
user=MemoUser('bitcoincash:used an address here')
user.private_key  = 'used WIF Compressed here'
user.get_memos()

Gets 
Traceback (most recent call last):
  File "get_posts.py", line 5, in <module>
    user.get_memos()
  File "/home/my_dir/.local/lib/python3.6/site-packages/bchmemo/memouser.py", line 61, in get_memos
    total_txs,txs=NetworkAPI.get_transactions_by_addresses(self._address)
  File "/home/my_dir/.local/lib/python3.6/site-packages/bchmemo/bitcash_modified/services.py", line 575, in get_transactions_by_addresses
    raise ConnectionError('All APIs are unreachable.')
ConnectionError: All APIs are unreachable.

Is this package abandoned?

**Comment by zdavatz** [comment]
looks like it ;)
